#!/bin/sh

set -e

for topic in $(git branchless --topics)
do
	remote=$(
		git config branch.$topic.pushRemote ||
		git config remote.pushDefault ||
		echo origin
	)
	git push $remote $topic "$@"
done
